print('hello world!')
print('whats your name ?')
myName=input()
print('it is  good to meet you,'+myName )
print('the length of you name is :')
print(len(myName))
print('what is your age ?')
myAge=input()
print('you will be '+ str(int(myAge)+1)+'in a year')